'use client';
import { useState } from "react";
export default function Home() {
 const [status,setStatus] = useState("");
 async function submit(e: React.FormEvent<HTMLFormElement>) {
  e.preventDefault(); setStatus("Sending your request…");
  const form = e.currentTarget; const data = Object.fromEntries(new FormData(form).entries());
  try {
   const r = await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
   const j = await r.json();
   if(!r.ok) throw new Error(j.error || "Please try again.");
   setStatus("Request received. RoofRank NJ will follow up soon."); form.reset();
  } catch(err) { setStatus(err instanceof Error ? err.message : "Could not send your request. Please try again."); }
 }
 return <main>
  <nav className="nav wrap"><a className="brand" href="#"><span className="brandmark">R</span><span>ROOFRANK <b>NJ</b><small>NEW JERSEY ROOFING NETWORK</small></span></a><a className="navcta" href="#estimate">Get an Estimate <span>↗</span></a></nav>
  <section className="hero"><div className="heroShade"></div><div className="wrap heroContent"><div className="eyebrow"><i></i> NEW JERSEY ROOFING, MADE SIMPLE</div><h1>Your roof.<br/><em>Your choice.</em><br/>Start with confidence.</h1><p>Find roofing help for repairs, replacement, inspections, and storm damage—right here in New Jersey.</p><div className="heroActions"><a className="button gold" href="#estimate">Request a Free Estimate <span>→</span></a><a className="textlink" href="#how">How it works <span>↓</span></a></div><div className="trustline"><span>◆</span> One request. Local options. Your decision.</div></div><div className="heroTag"><b>ROOFRANK NJ</b><span>BUILT FOR NEW JERSEY HOMEOWNERS</span></div></section>
  <section className="proof"><div className="wrap proofgrid"><div><strong>01</strong><span>Tell us what your roof needs</span></div><div><strong>02</strong><span>We route your request to relevant pros</span></div><div><strong>03</strong><span>Compare your options and choose</span></div></div></section>
  <section className="section wrap" id="how"><div className="sectionhead"><div className="eyebrow dark">A BETTER STARTING POINT</div><h2>Roofing help, without<br/><em>the runaround.</em></h2><p>Whether it’s a small leak or a full replacement, start with one simple request.</p></div><div className="servicegrid"><article><span className="serviceicon">⌂</span><h3>Roof Repair</h3><p>Leaks, missing shingles, flashing, and other roof issues.</p></article><article><span className="serviceicon">↗</span><h3>Roof Replacement</h3><p>Explore options for a new roof and project estimates.</p></article><article><span className="serviceicon">◈</span><h3>Storm Damage</h3><p>Request help assessing damage after severe weather.</p></article><article><span className="serviceicon">◎</span><h3>Roof Inspection</h3><p>Get a closer look before buying, selling, or repairing.</p></article></div></section>
  <section className="estimate" id="estimate"><div className="wrap estimategrid"><div className="estimatecopy"><div className="eyebrow"><i></i> GET STARTED</div><h2>Let’s get your roof<br/><em>back on track.</em></h2><p>Share a few details. We’ll use them to help connect your request with participating roofing companies that serve your area.</p><div className="privacyNote"><span>◈</span><p><b>Your request, handled with care.</b><br/>Your contact and project details may be shared with relevant participating roofing companies so they can respond to your request.</p></div></div>
  <form className="leadform" onSubmit={submit}><div className="formtitle"><span>HOMEOWNER REQUEST</span><b>Tell us about your project</b></div><div className="formrow"><label>Full name<input name="name" required autoComplete="name" placeholder="Your name"/></label><label>Phone number<input name="phone" required type="tel" autoComplete="tel" placeholder="(555) 555-5555"/></label></div><label>Email address<input name="email" required type="email" autoComplete="email" placeholder="you@example.com"/></label><div className="formrow"><label>New Jersey ZIP code<input name="zip" required inputMode="numeric" pattern="[0-9]{5}" placeholder="07001"/></label><label>Property type<select name="property_type" required defaultValue=""><option value="" disabled>Select type</option><option>Single-family home</option><option>Townhouse</option><option>Multi-family</option><option>Commercial</option><option>Other</option></select></label></div><label>What do you need?<select name="service" required defaultValue=""><option value="" disabled>Choose a service</option><option>Roof repair</option><option>Roof replacement</option><option>Roof inspection</option><option>Storm damage</option><option>Gutter services</option><option>Not sure yet</option></select></label><label>When are you looking to start?<select name="timing" required defaultValue=""><option value="" disabled>Select timing</option><option>As soon as possible</option><option>Within 2 weeks</option><option>Within 1–3 months</option><option>Just researching</option></select></label><label>Project details <span className="optional">(optional)</span><textarea name="details" rows={3} placeholder="Tell us about the roof or issue…"/></label><label className="consent"><input type="checkbox" name="consent" value="yes" required/><span>I agree that RoofRank NJ may contact me about this request and share relevant project details with participating roofing companies.</span></label><button className="button gold submit" type="submit">Send My Request <span>→</span></button><p className="formstatus" role="status">{status}</p><small className="formfine">Submitting this form does not obligate you to hire any contractor.</small></form></div></section>
  <section className="rooferbar"><div className="wrap rooferinner"><div><div className="eyebrow dark">FOR ROOFING COMPANIES</div><h2>Grow your local pipeline.</h2><p>Interested in receiving homeowner requests in your service area?</p></div><a className="button darkbtn" href="/join">Join the RoofRank Network <span>→</span></a></div></section>
  <footer><div className="wrap footinner"><a className="brand" href="#"><span className="brandmark">R</span><span>ROOFRANK <b>NJ</b><small>NEW JERSEY ROOFING NETWORK</small></span></a><div className="footlinks"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/join">For Roofers</a></div><span className="copyright">© {new Date().getFullYear()} RoofRank NJ</span></div><div className="wrap disclaimer">RoofRank NJ helps homeowners connect with participating roofing companies. Contractor availability and qualifications should be confirmed directly before hiring.</div></footer>
 </main>;
}